### PR TITLE
Added #peek(count) to get more than 1 elements

### PR DESCRIPTION
**Pull request by jameshartig**
Use case: If you're building a chat server and want new clients to get the last 3 messages upon joining you would do something like:

``` JS
var buffer = new RingBuffer(3);
function onJoin(client) {
    var msgs = buffer.peek(buffer.size());
    client.write(msgs.join("\n"));
}
```

I tested using `npm test` but couldn't test in the browser since I don't have the build directory I guess? It just kept complaining about `require()` not being defined.

### CODE REVIEW

**Comment by jameshartig** [comment]
Alternatively I could add a `forEach` method like what you approved here https://github.com/janogonzalez/priorityqueuejs/pull/3. We couldn't just fallback to `_elements.forEach` though so it'd have to be a custom implementation of `forEach`. Also, `forEach` isn't available in all browsers so a custom one would be needed to maintain browser compat.

Let me know if you prefer `peek` or `forEach`.

**Comment by jameshartig** [comment]
Any update on this?

**Comment by janogonzalez** [comment]
Maybe returning either an item or an array from the function will be confusing, what about a `peekN(n)` function or something?

**Comment by janogonzalez** [comment]
closing for lack of activity

**Pull request closed without merging**
