### PR TITLE
Add peekN and deqN to peek/deq multiple elements

### PR DESCRIPTION
**Pull request by bfirsh**
A follow-up of #1. Hopefully more efficient by using the native `slice()` instead of for loops.

### CODE REVIEW

**Comment by janogonzalez** [comment]
thanks for the PR!

**Comment by bfirsh** [comment]
ping @janogonzalez :)

**Comment by janogonzalez** [comment]
I'll take a look, thx :)

**Comment by janogonzalez** [comment]
Looks good, thank you!

**Pull request merged**
